# pubspec.yaml
name: dementialink
description: "Software Development Group Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.34
  google_sign_in: ^6.1.6
  firebase_storage: ^11.5.6
  image_picker: ^1.0.7
  cloud_firestore: ^4.13.6      # Add this
  google_generative_ai: ^0.1.0   # Add this
  uuid: ^4.2.1
  flutter_riverpod: ^2.4.10
  flutter_dotenv: ^5.1.0
  flutter_tts: ^3.8.5
  speech_to_text: ^6.5.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/i1.png
    - assets/images/i2.png
    - assets/images/i3.png
    - assets/images/i4.png
    - assets/images/i5.jpg
    - assets/images/brain_icon.png
    - assets/audio/track1.mp3
    - assets/audio/track2.mp3
    - assets/audio/track3.mp3
    - assets/audio/track4.mp3
    - assets/audio/track5.mp3
    - assets/icons/googlelogo.png
    - assets/icons/brain.png
    - .env