# pubspec.yaml
name: dementialink
description: "Software Development Group Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.34
  intl: ^0.18.0  # For date formatting
  provider: ^6.0.5
  # Backend integration
  http: ^1.1.0
  shared_preferences: ^2.2.0
  device_info_plus: ^9.0.2
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^15.1.0+1
  # Added for notifications
  timezone: ^0.9.2  # For timezone-aware scheduling of notifications
  rxdart: ^0.27.7    # For stream transformations and scheduling

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add notification sounds
  assets:
    - assets/sounds/task_alarm.mp3

  # Add notification icons
  # android/app/src/main/res/drawable/notification_icon.png