# pubspec.yaml
name: dementialink
description: "Software Development Group Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.34
  intl: ^0.18.0  # For date formatting
  provider: ^6.0.5
  flutter_speech: ^2.0.1  # For speech recognition
  flutter_tts: ^3.8.5  # For text-to-speech responses
  permission_handler: ^10.4.5 # For handling microphone permissions
  # Backend integration
  http: ^1.1.0
  shared_preferences: ^2.2.0
  device_info_plus: ^9.0.2
  firebase_messaging: ^14.7.0
  #  flutter_local_notifications: ^15.1.0+1
  flutter_local_notifications: ^16.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/i1.png
    - assets/images/i2.png
    - assets/images/i3.png
    - assets/images/i4.png
    - assets/images/i5.jpg
    - assets/images/brain_icon.png
    - assets/audio/track1.mp3
    - assets/audio/track2.mp3
    - assets/audio/track3.mp3
    - assets/audio/track4.mp3
    - assets/audio/track5.mp3