# pubspec.yaml
name: dementialink
description: "Software Development Group Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.2
  firebase_storage: ^11.7.7
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/apple_logo.png
    - lib/assets/brain_logo.png
    - lib/assets/facebook_logo.png
    - lib/assets/google_logo.png
    - lib/assets/intro1.png
    - lib/assets/intro2.png
    - lib/assets/intro3.png
    - lib/assets/intro4.png
    - lib/assets/msg.png
    - lib/assets/profile_setup.png
    - lib/assets/patient_profile.png

 
