# pubspec.yaml
name: dementialink
description: "Software Development Group Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.17.9
  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  permission_handler: ^10.4.3
  firebase_database: ^10.0.15
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/back_arrow.png
    - assets/location_pin.png
    - assets/logo.png
    - assets/mic.png
    - assets/google-maps.png

